AllCops:
  TargetRubyVersion: 2.6.4

AllCops:
  Exclude:
    - seed.rb
    - Readme.md
    - .gitignore

Style/Documentation:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Layout/LineLength:
  Max: 90

Style/ClassVars:
  Enabled: false

Lint/RedundantStringCoercion:
  Enabled: false
